### ISSUE TITLE
 terraform-oci-arch-tomcat-mds

### ISSUE THREAD

**Issue by nvseven** [oracle-devrel/terraform-oci-arch-tomcat-mds#3]
This looks straight forward but                                                                                              
Deploy Using Oracle Resource Manager
Click Deploy to Oracle Cloud

If you aren't already signed in, when prompted, enter the tenancy and user credentials.

Review and accept the terms and conditions.

Select the region where you want to deploy the stack.

Follow the on-screen prompts and instructions to create the stack.

After creating the stack, click Terraform Actions, and select Plan.

Wait for the job to be completed, and review the plan.

To make any changes, return to the Stack Details page, click Edit Stack, and make the required changes. Then, run the Plan action again.

If no further changes are necessary, return to the Stack Details page, click Terraform Actions, and select Apply.                       
Error: Attempt to index null value
  on provider.tf line 22, in provider "oci" 
  22:   region               = data.oci_identity_region_subscriptions.home_region_subscriptions.region_subscriptions[0].region_name
    |----------------
    | data.oci_identity_region_subscriptions.home_region_subscriptions.region_subscriptions is null
This value is null, so it does not have any indices.
_________________________________________________________________________________________________________
This can be fixed by manually specifying var.region for region and then additional error will pop up 

oci_identity_tag_namespace.ArchitectureCenterTagNamespace: Creating...
Error: 403-NotAllowed
Provider version: 4.65.0, released on 2022-02-23.
Service: Identity Tag Namespace
Error Message: Please go to your home region iad to execute CREATE, UPDATE and DELETE operations.
OPC request ID: dec33fc2b32833c70b2e9a3587b60a98/B7290952BA04B2B0FF212B233A4D3989/3928E4E2603CED69B7EC4CA040D54E17
Suggestion: Please retry or contact support for help with service: Identity Tag Namespace
  on tags.tf line 8, in resource "oci_identity_tag_namespace" "ArchitectureCenterTagNamespace" 
   8: resource "oci_identity_tag_namespace" "ArchitectureCenterTagNamespace" {

**Comment by lfeldman** [comment]
@nvseven we have seen this kind of error when the user was not granted proper privileges. Could you confirm? Can you see tag namespaces in the console:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/19390609/156370371-3f33a60b-82d3-4388-aab0-d534dab4ffb1.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/19390609/156370438-89529cf6-aed5-4767-b3f4-27b98031e3eb.png">

**Comment by lfeldman** [comment]
In the case of the regions could you confirm you can access regions management in the Console?

<img width="876" alt="image" src="https://user-images.githubusercontent.com/19390609/156371118-720aec43-7b60-408b-8d3b-472c413e1a5e.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/19390609/156371160-6fdc6a48-edf8-489a-9abc-3f3e7ab18221.png">

**Comment by nvseven** [comment]
> 

i can see regions from region management
![image](https://user-images.githubusercontent.com/12674220/156371498-1924a759-4f0c-4754-bdad-e02182c8d08e.png)

**Comment by nvseven** [comment]
> @nvseven we have seen this kind of error when the user was not granted proper privileges. Could you confirm? Can you see tag namespaces in the console:
> 
> <img alt="image" width="896" src="https://user-images.githubusercontent.com/19390609/156370371-3f33a60b-82d3-4388-aab0-d534dab4ffb1.png">
> 
> <img alt="image" width="876" src="https://user-images.githubusercontent.com/19390609/156370438-89529cf6-aed5-4767-b3f4-27b98031e3eb.png">

i have empty tag namespace, can you provide list of namespaces i should add
![image](https://user-images.githubusercontent.com/12674220/156372435-9728eb1b-c3a4-4066-83b5-3f6ec6fa433d.png)

**Comment by nvseven** [comment]
Please close this issue, no further assistance needed. I managed to run the stack on home region.
